
import java.awt.Color;
import java.awt.Dimension;
import java.sql.*;
import javax.swing.*;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

import javax.swing.JFrame;
import javax.swing.JTextField;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MF1.java
 *
 * Created on Dec 20, 2015, 4:08:25 PM
 */


/**
 *
 * @author burhanudin
 */
public class MF1 extends javax.swing.JFrame {

    /** Creates new form MF1 */
    public MF1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1030, 640));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(923, 0, 110, 30);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 303, 1030, 5);
        jSeparator1.getAccessibleContext().setAccessibleDescription("");

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/logout-512.png"))); // NOI18N
        jButton4.setActionCommand("Logout ");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setDefaultCapable(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(5, 60, 104, 140);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Logout");
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setInheritsPopupMenu(false);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 170, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Add to Cart");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(914, 150, 81, 17);

        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(910, 70, 90, 110);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("<html>Click on respective images to Select them, and click Cart Button on<b> Top Left</b>");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 180, 630, 36);

        jButton2.setBackground(new java.awt.Color(217, 66, 85));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View Shopping History");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 220, 210, 30);

        jPanel1.setPreferredSize(new java.awt.Dimension(1030, 1200));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Electronics", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(null);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(jLabel38);
        jLabel38.setBounds(4, 0, 250, 190);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/images (3).jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.add(jLabel5);
        jLabel5.setBounds(4, 0, 250, 190);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Air Conditioner");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel7);
        jLabel7.setBounds(10, 200, 230, 30);

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("10000");
        jLabel54.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel54);
        jLabel54.setBounds(80, 230, 90, 30);

        jPanel2.add(jPanel6);

        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });
        jPanel7.setLayout(null);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel39.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel39);
        jLabel39.setBounds(4, 0, 250, 190);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/images (4).jpg"))); // NOI18N
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel8);
        jLabel8.setBounds(4, 0, 250, 190);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Laptop-OS:Windows");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel9);
        jLabel9.setBounds(10, 200, 230, 30);

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("40000");
        jLabel55.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel55);
        jLabel55.setBounds(80, 230, 90, 30);

        jPanel2.add(jPanel7);

        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });
        jPanel8.setLayout(null);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel40);
        jLabel40.setBounds(4, 0, 250, 190);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/images (5).jpg"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel10);
        jLabel10.setBounds(4, 0, 250, 190);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Speakers");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel11);
        jLabel11.setBounds(10, 200, 230, 30);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("5000");
        jLabel56.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel56);
        jLabel56.setBounds(80, 230, 90, 30);

        jPanel2.add(jPanel8);

        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
        });
        jPanel9.setLayout(null);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(jLabel41);
        jLabel41.setBounds(4, 0, 250, 190);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/unnamed.png"))); // NOI18N
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel9.add(jLabel12);
        jLabel12.setBounds(4, 0, 250, 190);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Samsung Galaxy Edge");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel13);
        jLabel13.setBounds(10, 200, 230, 30);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("25000");
        jLabel57.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel9.add(jLabel57);
        jLabel57.setBounds(80, 230, 90, 30);

        jPanel2.add(jPanel9);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Books", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });
        jPanel10.setLayout(null);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(jLabel42);
        jLabel42.setBounds(4, 0, 250, 190);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/NEET COMBO.jpg"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel10.add(jLabel14);
        jLabel14.setBounds(4, 0, 250, 190);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Neet Guide");
        jPanel10.add(jLabel15);
        jLabel15.setBounds(10, 200, 230, 30);

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("500");
        jPanel10.add(jLabel58);
        jLabel58.setBounds(80, 230, 90, 30);

        jPanel3.add(jPanel10);

        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });
        jPanel11.setLayout(null);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel43.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.add(jLabel43);
        jLabel43.setBounds(4, 0, 250, 190);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/51sldePALJL._SX258_BO1%2C204%2C203%2C200_.jpg"))); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.add(jLabel16);
        jLabel16.setBounds(4, 0, 250, 190);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("JEE Main Prepguide");
        jPanel11.add(jLabel17);
        jLabel17.setBounds(10, 200, 230, 30);

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("700");
        jPanel11.add(jLabel59);
        jLabel59.setBounds(80, 230, 90, 30);

        jPanel3.add(jPanel11);

        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(null);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel44.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.add(jLabel44);
        jLabel44.setBounds(4, 0, 250, 190);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/images (6).jpg"))); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.add(jLabel18);
        jLabel18.setBounds(4, 0, 250, 190);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Oliver Twist");
        jPanel12.add(jLabel19);
        jLabel19.setBounds(10, 200, 230, 30);

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("400");
        jPanel12.add(jLabel60);
        jLabel60.setBounds(80, 230, 90, 30);

        jPanel3.add(jPanel12);

        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(null);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.add(jLabel45);
        jLabel45.setBounds(4, 0, 250, 190);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/images (7).jpg"))); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.add(jLabel20);
        jLabel20.setBounds(4, 0, 250, 190);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Diary of a Young Girl");
        jPanel13.add(jLabel21);
        jLabel21.setBounds(10, 200, 230, 30);

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("450");
        jPanel13.add(jLabel61);
        jLabel61.setBounds(80, 230, 90, 30);

        jPanel3.add(jPanel13);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stationery", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(null);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        jPanel14.add(jLabel46);
        jLabel46.setBounds(4, 0, 250, 190);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/images (8).jpg"))); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(jLabel22);
        jLabel22.setBounds(4, 0, 250, 190);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Parker Pen");
        jPanel14.add(jLabel23);
        jLabel23.setBounds(10, 200, 230, 30);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("200");
        jPanel14.add(jLabel62);
        jLabel62.setBounds(80, 230, 90, 30);

        jPanel4.add(jPanel14);

        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });
        jPanel15.setLayout(null);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(jLabel47);
        jLabel47.setBounds(4, 0, 250, 190);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/images (9).jpg"))); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(jLabel24);
        jLabel24.setBounds(4, 0, 250, 190);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Eraser");
        jPanel15.add(jLabel25);
        jLabel25.setBounds(10, 200, 230, 30);

        jLabel63.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("20");
        jPanel15.add(jLabel63);
        jLabel63.setBounds(80, 230, 90, 30);

        jPanel4.add(jPanel15);

        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
        });
        jPanel16.setLayout(null);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.add(jLabel48);
        jLabel48.setBounds(4, 0, 250, 190);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/images (10).jpg"))); // NOI18N
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.add(jLabel26);
        jLabel26.setBounds(4, 0, 250, 190);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Orange Pouch");
        jPanel16.add(jLabel27);
        jLabel27.setBounds(10, 200, 230, 30);

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("100");
        jPanel16.add(jLabel64);
        jLabel64.setBounds(80, 230, 90, 30);

        jPanel4.add(jPanel16);

        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel17MouseClicked(evt);
            }
        });
        jPanel17.setLayout(null);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel49.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.add(jLabel49);
        jLabel49.setBounds(4, 0, 250, 190);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/images (11).jpg"))); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.add(jLabel28);
        jLabel28.setBounds(4, 0, 250, 190);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("HB Pencils");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel17.add(jLabel29);
        jLabel29.setBounds(10, 200, 230, 30);

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("50");
        jPanel17.add(jLabel65);
        jLabel65.setBounds(80, 230, 90, 30);

        jPanel4.add(jPanel17);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Toys", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel5.setRequestFocusEnabled(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
        });
        jPanel18.setLayout(null);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.add(jLabel50);
        jLabel50.setBounds(4, 0, 250, 190);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/Car.jpg"))); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.add(jLabel30);
        jLabel30.setBounds(4, 0, 250, 190);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Remote Controlled Car");
        jPanel18.add(jLabel31);
        jLabel31.setBounds(10, 200, 230, 30);

        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("2500");
        jPanel18.add(jLabel66);
        jLabel66.setBounds(80, 230, 90, 30);

        jPanel5.add(jPanel18);

        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel19MouseClicked(evt);
            }
        });
        jPanel19.setLayout(null);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel19.add(jLabel51);
        jLabel51.setBounds(4, 0, 250, 190);

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/Woody Mask.jpg"))); // NOI18N
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel19.add(jLabel32);
        jLabel32.setBounds(4, 0, 250, 190);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Woody Mask");
        jPanel19.add(jLabel33);
        jLabel33.setBounds(10, 200, 230, 30);

        jLabel67.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("400");
        jPanel19.add(jLabel67);
        jLabel67.setBounds(80, 230, 90, 30);

        jPanel5.add(jPanel19);

        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel20MouseClicked(evt);
            }
        });
        jPanel20.setLayout(null);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel52.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel20.add(jLabel52);
        jLabel52.setBounds(4, 0, 250, 190);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/Yo-Yo.jpg"))); // NOI18N
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel20.add(jLabel34);
        jLabel34.setBounds(4, 0, 250, 190);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Yo-Yo");
        jPanel20.add(jLabel35);
        jLabel35.setBounds(10, 200, 230, 30);

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("300");
        jPanel20.add(jLabel68);
        jLabel68.setBounds(80, 230, 90, 30);

        jPanel5.add(jPanel20);

        jPanel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel21MouseClicked(evt);
            }
        });
        jPanel21.setLayout(null);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/tick.png"))); // NOI18N
        jLabel53.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel21.add(jLabel53);
        jLabel53.setBounds(4, 0, 250, 190);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/Helicopter.jpg"))); // NOI18N
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel21.add(jLabel36);
        jLabel36.setBounds(4, 0, 250, 190);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Mechanical Helicopter");
        jPanel21.add(jLabel37);
        jLabel37.setBounds(10, 200, 230, 30);

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("6000");
        jPanel21.add(jLabel69);
        jLabel69.setBounds(80, 230, 90, 30);

        jPanel5.add(jPanel21);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 307, 1025, 300);
        jScrollPane1.getAccessibleContext().setAccessibleDescription("");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField1.setText("Welcome");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(355, 260, 145, 44);

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField3.setBorder(null);
        jTextField3.setOpaque(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(500, 260, 130, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/MF1.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseMoved

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK));
        
        try{
Class.forName("java.sql.Driver");
Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
Statement st=conn.createStatement();

ResultSet rs=st.executeQuery("Select username from signhistory order by username_id desc limit 1;");
        
       
        while(rs.next()){
       String username=rs.getString("username");
            jTextField3.setText(username);}
        }
        
        
        
        catch(Exception e){
        
        }
        
        jTextField1.setOpaque(true);
        jTextField3.setOpaque(true);
        
         jButton3.setOpaque(false);
jButton3.setContentAreaFilled(false);

jButton1.setOpaque(false);
jButton1.setContentAreaFilled(false);

jLabel38.setVisible(false);
jLabel39.setVisible(false);
jLabel40.setVisible(false);
jLabel41.setVisible(false);
jLabel42.setVisible(false);
jLabel43.setVisible(false);
jLabel44.setVisible(false);
jLabel45.setVisible(false);
jLabel46.setVisible(false);
jLabel47.setVisible(false);
jLabel48.setVisible(false);
jLabel49.setVisible(false);
jLabel50.setVisible(false);
jLabel51.setVisible(false);
jLabel52.setVisible(false);
jLabel53.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new userhistory().setVisible(true);

        try{
            Class.forName("java.sql.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
            Statement st=conn.createStatement();
            st.executeUpdate("insert into userhistory(username) values('"+jTextField3.getText()+"');");

        }
        catch(Exception e){

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new cart().setVisible(true);

        if(jLabel38.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel7.getText()+"','"+jLabel54.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel39.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel9.getText()+"','"+jLabel55.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel40.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel11.getText()+"','"+jLabel56.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel41.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel13.getText()+"','"+jLabel57.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel42.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel15.getText()+"','"+jLabel58.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }

        if(jLabel43.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel17.getText()+"','"+jLabel59.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel44.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel19.getText()+"','"+jLabel60.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel45.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel21.getText()+"','"+jLabel61.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel46.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel23.getText()+"','"+jLabel62.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel47.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel25.getText()+"','"+jLabel63.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel48.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel27.getText()+"','"+jLabel64.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel49.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel29.getText()+"','"+jLabel65.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel50.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel31.getText()+"','"+jLabel66.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel51.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel33.getText()+"','"+jLabel67.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel52.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel35.getText()+"','"+jLabel68.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
        
        if(jLabel53.isVisible()==true){
            try{
                Class.forName("java.sql.Driver");
                Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
                Statement st=conn.createStatement();

                st.executeUpdate("Insert into hhh values('"+jLabel37.getText()+"','"+jLabel69.getText()+"');");
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());

            }
        }
       
        
        try{
            Class.forName("java.sql.Driver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
            Statement st=conn.createStatement();
            st.executeUpdate("Insert into carthistory(username) Values(' "+jTextField3.getText()+"');");
        }
        catch(Exception e){

        }
                                            

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        if(jLabel38.isVisible()==true){
        jLabel38.setVisible(false);
        }
        else{
        jLabel38.setVisible(true);
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        if(jLabel39.isVisible()==true){
        jLabel39.setVisible(false);
        }
        else{
        jLabel39.setVisible(true);
        }
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        if(jLabel40.isVisible()==true){
        jLabel40.setVisible(false);
        }
        else{
        jLabel40.setVisible(true);
        }
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        if(jLabel41.isVisible()==true){
        jLabel41.setVisible(false);
        }
        else{
        jLabel41.setVisible(true);
        }
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new home_pg().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
        if(jLabel42.isVisible()==true){
        jLabel42.setVisible(false);
        }
        else{
        jLabel42.setVisible(true);
        }
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
        if(jLabel43.isVisible()==true){
        jLabel43.setVisible(false);
        }
        else{
        jLabel43.setVisible(true);
        }
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
        if(jLabel44.isVisible()==true){
        jLabel44.setVisible(false);
        }
        else{
        jLabel44.setVisible(true);
        }
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
        if(jLabel45.isVisible()==true){
        jLabel45.setVisible(false);
        }
        else{
        jLabel45.setVisible(true);
        }
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
        if(jLabel46.isVisible()==true){
        jLabel46.setVisible(false);
        }
        else{
        jLabel46.setVisible(true);
        }
        
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
        if(jLabel47.isVisible()==true){
        jLabel47.setVisible(false);
        }
        else{
        jLabel47.setVisible(true);
        }
        
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
        // TODO add your handling code here:
        if(jLabel48.isVisible()==true){
        jLabel48.setVisible(false);
        }
        else{
        jLabel48.setVisible(true);
        }
        
    }//GEN-LAST:event_jPanel16MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        // TODO add your handling code here:
        if(jLabel46.isVisible()==true){
        jLabel46.setVisible(false);
        }
        else{
        jLabel46.setVisible(true);
        }
    }//GEN-LAST:event_jLabel46MouseClicked

    private void jPanel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseClicked
        // TODO add your handling code here:
        if(jLabel49.isVisible()==true){
        jLabel49.setVisible(false);
        }
        else{
        jLabel49.setVisible(true);
        }
    }//GEN-LAST:event_jPanel17MouseClicked

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        // TODO add your handling code here:
        if(jLabel50.isVisible()==true){
        jLabel50.setVisible(false);
        }
        else{
        jLabel50.setVisible(true);
        }
    }//GEN-LAST:event_jPanel18MouseClicked

    private void jPanel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseClicked
        // TODO add your handling code here:
        if(jLabel51.isVisible()==true){
        jLabel51.setVisible(false);
        }
        else{
        jLabel51.setVisible(true);
        }
    }//GEN-LAST:event_jPanel19MouseClicked

    private void jPanel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseClicked
        // TODO add your handling code here:
        if(jLabel52.isVisible()==true){
        jLabel52.setVisible(false);
        }
        else{
        jLabel52.setVisible(true);
        }
    }//GEN-LAST:event_jPanel20MouseClicked

    private void jPanel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel21MouseClicked
        // TODO add your handling code here:
        if(jLabel53.isVisible()==true){
        jLabel53.setVisible(false);
        }
        else{
        jLabel53.setVisible(true);
        }
    }//GEN-LAST:event_jPanel21MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MF1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
