

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.*;
import java.sql.*;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * signup.java
 *
 * Created on Dec 31, 2015, 2:34:47 PM
 */

/**
 *
 * @author Welcome
 */
public class signup extends javax.swing.JFrame {

    /** Creates new form signup */
    public signup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        pass2 = new javax.swing.JPasswordField();
        pass1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(541, 577));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 140, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Already have an account?");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 500, 240, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("<html><body>Confirm<br>Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 280, 70, 34);

        jButton2.setBackground(new java.awt.Color(217, 66, 85));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign In");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 530, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 215, 80, 20);

        username.setBackground(new java.awt.Color(153, 217, 234));
        username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        username.setBorder(null);
        username.setCaretColor(new java.awt.Color(255, 255, 255));
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username.setOpaque(false);
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(210, 132, 220, 40);

        pass2.setBackground(new java.awt.Color(153, 217, 234));
        pass2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass2.setBorder(null);
        pass2.setCaretColor(new java.awt.Color(255, 255, 255));
        pass2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pass2.setOpaque(false);
        getContentPane().add(pass2);
        pass2.setBounds(210, 281, 220, 40);

        pass1.setBackground(new java.awt.Color(153, 217, 234));
        pass1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass1.setBorder(null);
        pass1.setCaretColor(new java.awt.Color(255, 255, 255));
        pass1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pass1.setOpaque(false);
        getContentPane().add(pass1);
        pass1.setBounds(210, 207, 220, 40);
        pass1.getAccessibleContext().setAccessibleDescription("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sign up Form");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(155, 30, 240, 49);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(101, 425, 340, 50);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(403, 495, 0, 0);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectivity/images/ippro/childrens/form.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 541, 577);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(username.getText().equals("hhh")||username.getText().equals("httf")||username.getText().equals("signhistory")||username.getText().equals("carthistory")||username.getText().equals("userhistory"))
        {
          JOptionPane.showMessageDialog(null,"The Username already exists, please enter another username");
        }
        else
        {
            
        
String user,p1,p2;
user=username.getText();
p1=pass1.getText();
p2=pass2.getText();
if (user.equals("")|| p1.equals("")||p2.equals("")){
    JOptionPane.showMessageDialog(null,"All fields are Mandatory, please fill them");
}


else{

if(p1.equals(p2)){
    
JOptionPane.showMessageDialog (null, "Your account has been successfully created!");


    String d2; d2=jLabel5.getText();
    if(d2.equals("")){
     this.setVisible(false);
     new MF1().setVisible(true);
     
     try{
Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
Statement st=conn.createStatement();
st.executeUpdate("create table "+username.getText()+"(a varchar(255),b int, date varchar(255));");
st.close();
conn.close();
}

catch(Exception e){
JOptionPane.showMessageDialog(this,e);
}

try{
Class.forName("java.sql.Driver");
Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
Statement st=conn.createStatement();
Statement st1=conn.createStatement();
st1.executeUpdate("Insert into httf(username,password) values('"+user+"','"+p1+"');");
st.executeUpdate("Insert into signhistory(username) Values(' "+username.getText()+"');");
st.close();
conn.close();
}

catch(Exception e){
JOptionPane.showMessageDialog(this,e);
}
}


    else{
    JOptionPane.showMessageDialog(null,"The Username already exists, please enter another username");
    jLabel5.setText("");
    username.setText("");
    pass1.setText("");
pass2.setText("");
    }


}


else{
JOptionPane.showMessageDialog(null,"Your passwords Do Not Match, Please enter them again");
pass1.setText("");
pass2.setText("");
}}
        }


 
}//GEN-LAST:event_jButton1ActionPerformed

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
        // TODO add your handling code here:
        jLabel5.setText("");

        try{
Class.forName("java.sql.Driver");
Connection conn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/sakila","root","123");
Statement st=conn.createStatement();

ResultSet rs=st.executeQuery("Select * from httf where username='"+username.getText()+"';");
while(rs.next()){
String d1=rs.getString("username");
jLabel5.setText(d1);
}
rs.close();
st.close();
conn.close();
}catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());

}
    }//GEN-LAST:event_usernameKeyReleased

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_usernameKeyPressed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
jButton1.setOpaque(true);
jButton1.setContentAreaFilled(false);
jButton1.setBorderPainted(false);
 Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.BLACK));
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Logg().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
